---
aap_component: ""
controller_status:
  state: "unknown"
eda_status:
  state: "unknown"
automation-controller:
  cert: "/etc/tower/tower.cert"
  ssl_key: "/etc/tower/tower.key"
automation-eda-controller:
  cert: "/etc/ansible-automation-platform/eda/server.cert"
  ssl_key: "/etc/ansible-automation-platform/eda/server.key"
